### PR TITLE
Remove liquidExitPenalty() function

### PR DESCRIPTION
**Pull request by skalermo**

### CODE REVIEW

**Review by vanruch — APPROVED** [review]

**Review by barrutko — APPROVED** [review]

**Review by yuchenlintt — COMMENTED** [review]
@hal909 Did we decide we want to remove the TrueFiPool2 liquidExitPenalty? I thought we only wanted to remove the penalty for TrueFiPool so that lenders in the legacy pool wouldn't be punished for exiting.

(If we do want to remove, then this PR LGTM.)

**Comment by vanruch** [comment]
I figured out that since we removed regular exit, we don't leave another choice and shouldn't be punishing anyone

**Review by hal909 — CHANGES_REQUESTED** [review]
We aren't supposed to remove liquid exit. Not approving this PR since we need to keep this function. You can close this PR

**Comment by vanruch** [comment]
@hal909 We are not removing liquid exit, but a penalty. What are we penalising now for?

**Comment by yuchenlintt** [comment]
> What are we penalising now for?

I think I can chime in here.

The reason there was no penalty for normal `exit()` was because lenders were withdrawing a _proportional_ amount of risk in LoanTokens. When calling `exit()` a lender wasn't increasing or decreasing the risk faced by other lenders.

My understanding is that `liquidExit()`'s penalty isn't meant to discourage it over `exit()` as a baseline. `liquidExit()` has a penalty because we don't want some lenders to abscond with all the liquid assets and leave the other pool lenders holding only loans (inherently more risky than stablecoins). It's a lender incentive to encourage healthy pool utilization, just like the utilization adjustment rate for borrowers.

We removed the liquid exit penalty for the legacy TrueFiPool as a gesture of good faith for lenders since we're asking them to migrate to the new tfTUSD pool.

I would be in favor of simplifying the penalty calculation so it doesn't need calculus and fixed precision logarithms, but we can take that discussion internal.

**Comment by mushroomsforest** [comment]
> 
> 
> > What are we penalising now for?
> 
> I think I can chime in here.
> 
> The reason there was no penalty for normal `exit()` was because lenders were withdrawing a _proportional_ amount of risk in LoanTokens. When calling `exit()` a lender wasn't increasing or decreasing the risk faced by other lenders.
> 
> My understanding is that `liquidExit()`'s penalty isn't meant to discourage it over `exit()` as a baseline. `liquidExit()` has a penalty because we don't want some lenders to abscond with all the liquid assets and leave the other pool lenders holding only loans (inherently more risky than stablecoins). It's a lender incentive to encourage healthy pool utilization, just like the utilization adjustment rate for borrowers.
> 
> We removed the liquid exit penalty for the legacy TrueFiPool as a gesture of good faith for lenders since we're asking them to migrate to the new tfTUSD pool.
> 
> I would be in favor of simplifying the penalty calculation so it doesn't need calculus and fixed precision logarithms, but we can take that discussion internal.

Hello TrueFi team. This is from Mushrooms Finance. We have a yield-farming strategy integrated with legacy TUSD lending pool (https://etherscan.io/address/0xa1e72267084192db7387c8cc1328fade470e4149) in TrueFi. However, seems this legacy TUSD pool (a proxy smart contract) change its underlying implementation FROM 0xda55fcf03af0a6d954ac06b995c8908076506b3a TO 0xefb7aeb1dc47c6834a2a30a698fa5ffa2a91f9aa and this change BREAK the smart contract abi we expected in our strategy, i.e., the latter impl smart contract lacks a function called liquidExitPenalty()  @yuchenlintt  @hal909  plz HELP

**Comment by yuchenlintt** [comment]
> Hello TrueFi team. This is from Mushrooms Finance. We have a yield-farming strategy integrated with legacy TUSD lending pool (https://etherscan.io/address/0xa1e72267084192db7387c8cc1328fade470e4149) in TrueFi. However, seems this legacy TUSD pool (a proxy smart contract) change its underlying implementation FROM `0xda55fcf03af0a6d954ac06b995c8908076506b3a` TO `0xefb7aeb1dc47c6834a2a30a698fa5ffa2a91f9aa` and this change BREAK the smart contract abi we expected in our strategy, i.e., the latter impl smart contract lacks a function called `liquidExitPenalty()` @yuchenlintt @hal909 plz HELP

Hi Mushrooms Finance,

Thank you for the report. As you mention, we did indeed upgrade our proxy and remove `liquidExitPenalty()` from our legacy tfTUSD lending pool. The reason for this removal is that we are in the process of deprecating this lending pool and asking our users to migrate to a new version: https://etherscan.io/address/0x97cE06c3e3D027715b2d6C22e67D5096000072E5. Our new tfTUSD pool still has a `liquidExitPenalty()` view function.

For more details on why we're migrating and our timeline, please read our blog post: https://blog.trusttoken.com/truefis-tftusd-pool-is-being-migrated-action-required-bece2601425c. And feel free to reach out on Discord if you have any further questions.


Yuchen

**Comment by mushroomsforest** [comment]
> 
> 
> > Hello TrueFi team. This is from Mushrooms Finance. We have a yield-farming strategy integrated with legacy TUSD lending pool (https://etherscan.io/address/0xa1e72267084192db7387c8cc1328fade470e4149) in TrueFi. However, seems this legacy TUSD pool (a proxy smart contract) change its underlying implementation FROM `0xda55fcf03af0a6d954ac06b995c8908076506b3a` TO `0xefb7aeb1dc47c6834a2a30a698fa5ffa2a91f9aa` and this change BREAK the smart contract abi we expected in our strategy, i.e., the latter impl smart contract lacks a function called `liquidExitPenalty()` @yuchenlintt @hal909 plz HELP
> 
> Hi Mushrooms Finance,
> 
> Thank you for the report. As you mention, we did indeed upgrade our proxy and remove `liquidExitPenalty()` from our legacy tfTUSD lending pool. The reason for this removal is that we are in the process of deprecating this lending pool and asking our users to migrate to a new version: https://etherscan.io/address/0x97cE06c3e3D027715b2d6C22e67D5096000072E5. Our new tfTUSD pool still has a `liquidExitPenalty()` view function.
> 
> For more details on why we're migrating and our timeline, please read our blog post: https://blog.trusttoken.com/truefis-tftusd-pool-is-being-migrated-action-required-bece2601425c. And feel free to reach out on Discord if you have any further questions.
> 
> Yuchen

The missing of `liquidExitPenalty` in legacy `tfTUSD`  due to this upgrade would cause our earning strategy stuck... I understand your purpose for this upgrade would be incentivize migration but I am not sure why it bring incompatibility. If possible, could you please add a dummy `liquidExitPenalty` which always `returns 10000 if no penalty` to make it backwards-compatible? I think there maybe some other protocols integrated with TrueFi may suffer similar issues. There is currently still $58M TUSD remain in that legacy tfTUSD pool.

**Comment by yuchenlintt** [comment]
> The missing of `liquidExitPenalty` in legacy `tfTUSD` due to this upgrade would cause our earning strategy stuck... I understand your purpose for this upgrade would be incentivize migration but I am not sure why it bring incompatibility. If possible, could you please add a dummy `liquidExitPenalty` which always `returns 10000 if no penalty` to make it backwards-compatible? I think there maybe some other protocols integrated with TrueFi may suffer similar issues. There is currently still $58M TUSD remain in that legacy tfTUSD pool.

Thank you for your concerns. Let's move this conversation to discord (if you don't mind), to avoid spamming other contributors to this PR.

**Pull request closed without merging**
