### PR TITLE
Remove minMintAmount argument from TrueFiPool flush

### PR DESCRIPTION
**Pull request by yuchenlintt**
This aligns TrueFiPool's slippage protections with TrueFiPool2 + CurveYearnStrategy, and makes automating CRV flushes with a keeper much simpler.

Compare `TrueFiPool.flush()` against `TrueFiPool2.flush()`:
https://github.com/trusttoken/smart-contracts/blob/c94ad4e2cc5aa2f4c3050d79eb75585065e287ba/contracts/truefi2/TrueFiPool2.sol#L488

Compare `TrueFiPool._curvePoolDeposit()` against `CurveYearnStrategy.deposit()`:
https://github.com/trusttoken/smart-contracts/blob/c94ad4e2cc5aa2f4c3050d79eb75585065e287ba/contracts/truefi2/strategies/CurveYearnStrategy.sol#L107

### CODE REVIEW

**Comment by vanruch** [comment]
The integration test is failing for curve deposits now. Maybe the minAmount is too big?

**Comment by yuchenlintt** [comment]
> The integration test is failing for curve deposits now. Maybe the minAmount is too big?

Yeah it failed 5 times in a row, which would imply an unacceptably high failure rate for us to use in practice.

I can't really do anything about the minMintAmount though. This PR was only intended to match the slippage behavior of TrueFiPool2, which also sets a 99.9% minMintAmount. I think we'll need @hal909's approval to lower that number.

**Review by vanruch — CHANGES_REQUESTED** [review]
So the problem is that you are putting the Curve LP tokens into the Gauge in `_curvePoolDeposit` and as a result the amount isn't changing and it fails on `exchangeProtector` modifier

**Comment by yuchenlintt** [comment]
Ah, that makes sense. I removed the `exchangeProtector` modifier so this implementation matches with `CurveYearnStrategy's.deposit()`. Running locally I got the integration test to pass.

**Comment by vanruch** [comment]
But now don't have any control if Curve really returns us the expected amount. Why not separate deposit part and gauge part and have guard only on the prior like we had before?

**Comment by yuchenlintt** [comment]
That's a fair point if we consider `_curvePoolDeposit()` in isolation, although this function is only called by `flush()`, which checks that `yTokenValue` doesn't slip too much.

I think there are two different approaches you and I are taking for this refactor, both reasonable:
1. your suggestion: make the minimum changes necessary to TrueFiPool
2. this PR: minimize the code divergence between TrueFiPool and {TrueFiPool2 + CurveYearnStrategy}

I would prefer (1) as well if we didn't have to maintain both TrueFiPool2 and TrueFiPool (which is hopefully only in the short term). However I think (2) is a little better in our current situation since it would help us backport any future changes we might need from TrueFiPool2 to TrueFiPool. Code duplication isn't ideal, but it's a compromise.

Let me know if you'd still prefer (1)! I'm happy to refactor this if you still think that's the best approach.

**Review by vanruch — APPROVED** [review]
Missed the yValue check, this PR looks good

**Review by hal909 — APPROVED** [review]

**Pull request merged**
